#!/bin/bash

cd /autograder/grader
mkdir /autograder/results
mkdir /autograder/source
find /autograder/submission -name '*.v' -not -name '*_test.v' -exec cp {} /autograder/source/ \;

uv run src/run_tests.py
